### ISSUE TITLE
Attributs manquants dans l'objet Conversation

### ISSUE THREAD

**Issue by DiesIrae** [RecastAI/SDK-python#4]
Bonjour,

J'ai remarqué l'absence de `sentiment` et `processing_language` dans l'object Conversation, contrairement à ce que la [documentation mentionne](https://github.com/RecastAI/SDK-python/wiki/02-Manage-conversation#conversation).

Ce n'est pas bloquant de notre côté, mais j'ai trouvé cela bizarre.

**Comment by ftriquet** [comment]
Bonjour @DiesIrae 
Après vérification, ces deux champs sont bien présents. Es-tu sûr d'avoir le SDK a jour (version 3.1.0)?
